#!/bin/bash
#SBATCH --job-name=dv-postprocess-variants
#SBATCH --output=dv-slurm-postprocess-variants-%j.out
#SBATCH --error=dv-slurm-postprocess-variants-%j.err
#SBATCH --time=1:00:00
#SBATCH --mem=100G
#SBATCH --cpus-per-task=4

echo ""
echo "### postprocess_variants ###"
echo "date: $(date)"
echo "node: $(hostname)"
echo "current dir: $(pwd)"
echo "----------------------------------"
module purge
module load singularity

# Postprocess variants. Output a VCF file out of call_variants_output.tfrecord.
# --infile: REQUIRED. Path(s) to CallVariantOutput protos to postprocess generated by call_variants.
# --outfile: REQUIRED. Path of the output VCF file.
# --ref: REQUIRED. Genome reference in FAI-indexed FASTA format.
set -x
time singularity exec --bind /scratch "$SIMG" \
  /opt/deepvariant/bin/postprocess_variants \
    --ref "$REF" \
    --infile "$CALL_VARIANTS_OUTPUT" \
    --outfile "$OUTPUT_VCF" \
    ${GVCF_TFRECORDS:+--nonvariant_site_tfrecord_path "$GVCF_TFRECORDS"} \
    ${OUTPUT_GVCF:+--gvcf_outfile "$OUTPUT_GVCF"}
STATUS=$?
set +x
